site_name: RL Learning Notes
site_description: Reinforcement learning math notes.
site_url: https://himmy-robotics.github.io/RL_Learning_Notes/
repo_url: https://github.com/Himmy-Robotics/RL_Learning_Notes
repo_name: Himmy-Robotics/RL_Learning_Notes

theme:
  name: material
  language: zh
  features:
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 强化学习的数学原理: index.md
